### ISSUE TITLE
`prepare_train_data.sh` fails

### ISSUE THREAD

**Issue by sia-cerebras** [allenai/open-instruct#20]
I get this error:
```
Splitting the ShareGPT dataset...
Traceback (most recent call last):
  File "scripts/split_sharegpt_conversations.py", line 117, in <module>
    main(args)
  File "scripts/split_sharegpt_conversations.py", line 96, in main
    tokenizer = transformers.AutoTokenizer.from_pretrained(
  File "XXX/venv/lib64/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 643, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "XXX/venv/lib64/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 487, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "XXX/venv/lib64/python3.8/site-packages/transformers/utils/hub.py", line 417, in cached_file
    resolved_file = hf_hub_download(
  File "XXX/venv/lib64/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "XXX/venv/lib64/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '../hf_llama_models/7B/'. Use `repo_type` argument if needed.
Reformatting the datasets...
Processing super_ni data...
Processing self_instruct data...
Processing unnatural_instructions data...
Processing stanford_alpaca data...
Processing dolly data...
Processing oasst1 data...
Processing code_alpaca data...
Processing gpt4_alpaca data...
Processing baize data...
Processing sharegpt data...
Traceback (most recent call last):
  File "open_instruct/reformat_datasets.py", line 452, in <module>
    globals()[f"convert_{subfolder}_data"](os.path.join(args.raw_data_dir, subfolder), os.path.join(args.output_dir, subfolder))
  File "open_instruct/reformat_datasets.py", line 301, in convert_sharegpt_data
    with open(os.path.join(data_dir, "sharegpt_html_cleaned_and_split.json"), "r") as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'data/raw_train/sharegpt/sharegpt_html_cleaned_and_split.json'```

**Comment by ningchaoar** [comment]
`../hf_llama_models/7B/` seems like a local model path which doesn't exist in this repo.
Try use `--model-name-or-path huggyllama/llama-7b` in `prepare_train_data.sh` and add `trust_remote=True` to `split_sharegpt_conversations.py` as well.
