### ISSUE TITLE
Errors running tulu3_dpo_8b.yaml

### ISSUE THREAD

**Issue by rghilduta** [allenai/open-instruct#469]
When I run "sh scripts/finetune_with_accelerate_config.sh 8 configs/train_configs/tulu3/tulu3_dpo_8b.yaml" I get :

```
Traceback (most recent call last):
  File "/home/ubuntu/open-instruct/open_instruct/finetune.py", line 1105, in <module>
    args = parser.parse()
  File "/home/ubuntu/open-instruct/open_instruct/utils.py", line 570, in parse
    output = self.parse_yaml_file(os.path.abspath(sys.argv[1]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/transformers/hf_argparser.py", line 423, in parse_yaml_file
    outputs = self.parse_dict(yaml.safe_load(Path(yaml_file).read_text()), allow_extra_keys=allow_extra_keys)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/transformers/hf_argparser.py", line 377, in parse_dict
    raise ValueError(f"Some keys are not used by the HfArgumentParser: {sorted(unused_keys)}")
ValueError: Some keys are not used by the HfArgumentParser: ['dpo_beta', 'dpo_loss_type']
```

I fixed this by adding:
```
    dpo_beta: float = field(
        default=0.1,  # or whatever default value you want
        metadata={"help": "The beta parameter for DPO loss"},
    )

    dpo_loss_type: str = field(
        default="sigmoid",  # or whatever default value you want
        metadata={"help": "The type of DPO loss to use"},
    )
```
around here: https://github.com/allenai/open-instruct/blob/main/open_instruct/finetune.py#L282 . But I'm not sure that's right.

Once I fix the DPO beta and DPO loss type variable issues training progresses only a bit further but stops with:
```
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/ubuntu/open-instruct/open_instruct/finetune.py", line 1115, in <module>
[rank0]:     main(args)
[rank0]:   File "/home/ubuntu/open-instruct/open_instruct/finetune.py", line 755, in main
[rank0]:     for index in random.sample(range(len(train_dataset)), 3):
[rank0]:   File "/usr/lib/python3.10/random.py", line 482, in sample
[rank0]:     raise ValueError("Sample larger than population or is negative")
[rank0]: ValueError: Sample larger than population or is negative
[rank7]: Traceback (most recent call last):
[rank7]:   File "/home/ubuntu/open-instruct/open_instruct/finetune.py", line 1115, in <module>
[rank7]:     main(args)
[rank7]:   File "/home/ubuntu/open-instruct/open_instruct/finetune.py", line 755, in main
[rank7]:     for index in random.sample(range(len(train_dataset)), 3):
[rank7]:   File "/usr/lib/python3.10/random.py", line 482, in sample
[rank7]:     raise ValueError("Sample larger than population or is negative")
[rank7]: ValueError: Sample larger than population or is negative
```

It turns out raw_datasets["train"] only contains a column "id" (with about 250k rows), that is removed by https://github.com/allenai/open-instruct/blob/main/open_instruct/utils.py#L390 
raw_datasets["train"] = raw_datasets["train"].remove_columns("id") 
ensuring the returned raw_datasets["train"] is empty. I think columns_to_keep is missing when calling get_datasets().

**Comment by natolambert** [comment]
Hey @rghilduta -- sorry, this is a typo in the command to run the job. It should be running with the script `dpo_tune`, the config mentioned in the readme points to `finetune` which is SFT. I've opened #471 to fix this.

**Comment by rghilduta** [comment]
yup that fixed it, thanks for the quick response @natolambert !
