### ISSUE TITLE
Issue of using DeepSpeed with ZeRO Stage 3 optimization

### ISSUE THREAD

**Issue by notoookay** [allenai/open-instruct#475]
Hi, I recently encountered an issue with training on multi-gpus. Basically, I train a cross-encoder model with DeepSpeed Zero 3, but the codebase is the same. Errors can be seen below, and it has been issued and solved at [this DeepSpeed issue](https://github.com/microsoft/DeepSpeed/issues/6793).

I don't know if you have encountered this issue, it works fine on one GPU. I tried with `deepspeed==0.15.0` as the `requirements.txt` and failed, but it works with `0.15.4`.

As the problem is shown very recently. Maybe you guys could check it out.

```
12/03/2024 07:54:53 - INFO - __main__ - ***** Running training *****
12/03/2024 07:54:53 - INFO - __main__ -   Num examples = 40723
12/03/2024 07:54:53 - INFO - __main__ -   Num Epochs = 2
12/03/2024 07:54:53 - INFO - __main__ -   Instantaneous batch size per device = 1
12/03/2024 07:54:53 - INFO - __main__ -   Total train batch size (w. parallel, distributed & accumulation) = 64
12/03/2024 07:54:53 - INFO - __main__ -   Gradient Accumulation steps = 32
12/03/2024 07:54:53 - INFO - __main__ -   Total optimization steps = 1274
  0%|                                                                                        | 0/1274 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/root/rag-ler-update/finetune_reranker.py", line 862, in <module>
    main()
  File "/root/rag-ler-update/finetune_reranker.py", line 750, in main
    with accelerator.accumulate(model):
  File "/root/miniconda3/envs/rag-ler/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/root/miniconda3/envs/rag-ler/lib/python3.10/site-packages/accelerate/accelerator.py", line 1064, in accumulate
    cm_stack.enter_context(contextlib.nullcontext() if allow_gradient_sync else self.no_sync(m))
  File "/root/miniconda3/envs/rag-ler/lib/python3.10/contextlib.py", line 492, in enter_context
    result = _cm_type.__enter__(cm)
  File "/root/miniconda3/envs/rag-ler/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/root/miniconda3/envs/rag-ler/lib/python3.10/site-packages/accelerate/accelerator.py", line 945, in no_sync
    with context():
  File "/root/miniconda3/envs/rag-ler/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/root/miniconda3/envs/rag-ler/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1995, in no_sync
    assert not self.zero_optimization_partition_gradients(), \
AssertionError: no_sync context manager is incompatible with gradient partitioning logic of ZeRO stage 3
[rank0]: Traceback (most recent call last):
[rank0]:   File "/root/rag-ler-update/finetune_reranker.py", line 862, in <module>
[rank0]:     main()
[rank0]:   File "/root/rag-ler-update/finetune_reranker.py", line 750, in main
[rank0]:     with accelerator.accumulate(model):
[rank0]:   File "/root/miniconda3/envs/rag-ler/lib/python3.10/contextlib.py", line 135, in __enter__
[rank0]:     return next(self.gen)
[rank0]:   File "/root/miniconda3/envs/rag-ler/lib/python3.10/site-packages/accelerate/accelerator.py", line 1064, in accumulate
[rank0]:     cm_stack.enter_context(contextlib.nullcontext() if allow_gradient_sync else self.no_sync(m))
[rank0]:   File "/root/miniconda3/envs/rag-ler/lib/python3.10/contextlib.py", line 492, in enter_context
[rank0]:     result = _cm_type.__enter__(cm)
[rank0]:   File "/root/miniconda3/envs/rag-ler/lib/python3.10/contextlib.py", line 135, in __enter__
[rank0]:     return next(self.gen)
[rank0]:   File "/root/miniconda3/envs/rag-ler/lib/python3.10/site-packages/accelerate/accelerator.py", line 945, in no_sync
[rank0]:     with context():
[rank0]:   File "/root/miniconda3/envs/rag-ler/lib/python3.10/contextlib.py", line 135, in __enter__
[rank0]:     return next(self.gen)
[rank0]:   File "/root/miniconda3/envs/rag-ler/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1995, in no_sync
[rank0]:     assert not self.zero_optimization_partition_gradients(), \
[rank0]: AssertionError: no_sync context manager is incompatible with gradient partitioning logic of ZeRO stage 3
```

**Comment by vwxyzjn** [comment]
Hi thanks for raising the issue. I can confirm out model was trained with deepspeed 0.15.0. Though deepspeed 0.15.4 will prob work just as well. 

If you want to replicate our exact setup, please follow the readme instructions.
